module Version exposing (..) -- where 
{-| This file is auto-generated by the Python script version.py. -} 


version : String 
version = "v1.5-25-g89bce27"

gitRepo : String 
gitRepo = "https://github.com/kgashok/elmBox"

