module Version exposing (..) -- where 
{-| This file is auto-generated by the Python script version.py. -} 


version : String 
version = "v1.0-25-g042c624"

gitRepo : String 
gitRepo = "https://github.com/kgashok/elmBox"

