module Version exposing (..) -- where 
{-| This file is auto-generated by the Python script version.py. -} 


version : String 
version = "v1.0-13-g2601fb4"

gitRepo : String 
gitRepo = "https://github.com/kgashok/elmBox"

