module Version exposing (..) -- where 
{-| This file is auto-generated by the Python script version.py. -} 


version : String 
version = "v1.6-35-g08e2b41"

gitRepo : String 
gitRepo = "https://github.com/kgashok/elmBox"

